# Этап сборки
FROM golang:1.22.5-alpine as builder
WORKDIR /build
COPY go.mod .
COPY go.sum .
RUN go mod download
COPY .. .
RUN go build -o /main ./cmd/main.go

# Финальный этап
FROM alpine:3
WORKDIR /app
COPY --from=builder /main /bin/main
COPY --from=builder /bin/.env /bin/.env
ENTRYPOINT ["/bin/main"]