basePath: /
definitions:
  entities.Campus:
    properties:
      address:
        type: string
      id:
        type: integer
      name:
        type: string
      university_id:
        type: integer
    type: object
  entities.Class:
    properties:
      academic_discipline_id:
        type: integer
      auditory_id:
        type: integer
      date:
        type: string
      group_names:
        items:
          type: string
        type: array
      id:
        type: integer
      name:
        type: string
      teacher_names:
        items:
          type: string
        type: array
      time_end:
        type: string
      time_start:
        type: string
      type:
        type: string
      week:
        type: integer
      weekday:
        type: integer
    type: object
  entities.CreateCampusesRequest:
    properties:
      address:
        type: string
      name:
        type: string
      university_id:
        type: integer
    type: object
  entities.CreateCampusesResponse:
    properties:
      id:
        type: integer
    type: object
  entities.CreateClassesRequest:
    properties:
      academic_discipline_id:
        type: integer
      auditory_id:
        type: integer
      date:
        type: string
      group_names:
        items:
          type: string
        type: array
      name:
        type: string
      teacher_names:
        items:
          type: string
        type: array
      time_end:
        type: string
      time_start:
        type: string
      type:
        type: string
      week:
        type: integer
      weekday:
        type: integer
    type: object
  entities.CreateClassesResponse:
    properties:
      id:
        type: integer
    type: object
  entities.CreateUniversityRequest:
    properties:
      name:
        type: string
    type: object
  entities.CreateUniversityResponse:
    properties:
      id:
        type: integer
    type: object
  entities.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  entities.University:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  entities.UpdateDeleteCampusResponse:
    properties:
      message:
        type: string
    type: object
  entities.UpdateDeleteClassResponse:
    properties:
      message:
        type: string
    type: object
  entities.UpdateDeleteUniversityResponse:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
  title: VUZ+ API
  version: "1.0"
paths:
  /campus:
    post:
      consumes:
      - application/json
      parameters:
      - description: campus data
        in: body
        name: data
        required: true
        schema:
          items:
            $ref: '#/definitions/entities.CreateCampusesRequest'
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entities.CreateCampusesResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
      summary: Create campuses
      tags:
      - campus
    put:
      consumes:
      - application/json
      parameters:
      - description: campus data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entities.Campus'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.UpdateDeleteCampusResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
      summary: Update campus
      tags:
      - campus
  /campus/address/{address}:
    get:
      consumes:
      - application/json
      parameters:
      - description: campus address
        in: path
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.Campus'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
      summary: Get campus by address
      tags:
      - campus
  /campus/all:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entities.Campus'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
      summary: Get all campuses
      tags:
      - campus
  /campus/id/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: campus id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.Campus'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
      summary: Get campus by id
      tags:
      - campus
  /campus/name/{name}:
    get:
      consumes:
      - application/json
      parameters:
      - description: campus name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.Campus'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
      summary: Get campus by name
      tags:
      - campus
  /campus/university_id/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: campus university_id
        in: path
        name: university_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.Campus'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
      summary: Get campus by university_id
      tags:
      - campus
  /campus{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: campus id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.UpdateDeleteCampusResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
      summary: Delete campus
      tags:
      - campus
  /class:
    post:
      consumes:
      - application/json
      parameters:
      - description: class data
        in: body
        name: data
        required: true
        schema:
          items:
            $ref: '#/definitions/entities.CreateClassesRequest'
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entities.CreateClassesResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
      summary: Create classes
      tags:
      - class
    put:
      consumes:
      - application/json
      parameters:
      - description: class data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entities.Class'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.UpdateDeleteClassResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
      summary: Update class
      tags:
      - class
  /class/auditory_id/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: class auditory id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.Class'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
      summary: Get class by auditory id
      tags:
      - class
  /class/group_name/{name}:
    get:
      consumes:
      - application/json
      parameters:
      - description: class group name
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.Class'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
      summary: Get class by group name
      tags:
      - class
  /class/id/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: class id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.Class'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
      summary: Get class by id
      tags:
      - class
  /class/teacher_name/{name}:
    get:
      consumes:
      - application/json
      parameters:
      - description: class teacher name
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.Class'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
      summary: Get class by teacher name
      tags:
      - class
  /class{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: class id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.UpdateDeleteClassResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
      summary: Delete class
      tags:
      - class
  /university:
    post:
      consumes:
      - application/json
      parameters:
      - description: university data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entities.CreateUniversityRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.CreateUniversityResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
      summary: Create university
      tags:
      - university
    put:
      consumes:
      - application/json
      parameters:
      - description: university data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entities.University'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.UpdateDeleteUniversityResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
      summary: Update university
      tags:
      - university
  /university/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: university id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.UpdateDeleteUniversityResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
      summary: Delete university
      tags:
      - university
  /university/all:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entities.University'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
      summary: Get all universities
      tags:
      - university
  /university/name/{name}:
    get:
      consumes:
      - application/json
      parameters:
      - description: university name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.University'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.ErrorResponse'
      summary: Get university by name
      tags:
      - university
swagger: "2.0"
