name: Deploy to Server

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.NODE1_SSH_PRIVATE_KEY }}

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no -p ${{ vars.NODE1_SSH_PORT }} ${{ vars.NODE1_SSH_USER }}@${{ secrets.NODE1_SERVER_IP }} << 'EOF'
          cd ${{ vars.NODE1_PROJECT_PATH }}

          # Save local changes and pull the latest code
          git stash
          git pull origin main

          # Rebuild and deploy containers with zero downtime
          docker-compose up -d --build

          # Clean up any unused resources
          docker image prune -f
        EOF
