name: Deploy to Server

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    name: Deploy App
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ vars.USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          cd ${{ vars.PROJECT_PATH}}

          git stash
          git pull origin main

          docker-compose up -d --build

          docker image prune -f
        EOF
